version: '3.3'
services:
  client:
    build:
      context:  ./client/
      dockerfile: Dockerfile
    expose:
      - "90"
    ports:
      - "90:90"
    links:
      - socket-server
  socket-server:
    build:
      context:  ./server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
